const clientData = [
  {
    id: 1,
    name: "ANCHOR FUNDING, INC.",
    dba: "ANCHOR FUNDING, INC.",
    nmls: "343434",
    lei: "324762478sjdfgsfgshgsdfjh",
    address: {
      street: "1945 N. Elston Ave.",
      city: "Chicago",
      state: "IL",
      zip: "60642",
    },
    isApproved: "Yes",
    isDualApproved: "Yes",
    delegatedStatus: "Active",
    nonDelegatedStatus: "Active",
    delegatedApprovedDate: "10/11/2019",
    nonDelegatedApprovedDate: "12/31/2017",
    division: "MIDWEST",
    delegatedAe: "Amy Collett",
    nonDelegatedAe: "Amy Collett",
    delegatedAr: "Nancy Considine",
    nonDelegatedAr: "Nancy Considine",
    delegatedCrm: "Nathan Wehrheim",
    nonDelegatedCrm: "Valerie Grace",
    contacts: [
      {
        id: 1,
        firstName: "Cathy",
        lastName: "Hernandez",
        jobTitle: "Closing Manager",
        email: "cathyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 2,
        firstName: "Cindy",
        lastName: "Hesslau",
        jobTitle: "Underwriting Manager",
        email: "cindyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 3,
        firstName: "Danielle",
        lastName: "Brosman",
        jobTitle: "-",
        email: "dveltri@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Other",
      },
    ],
    status: "Active",
  },
  {
    id: 2,
    name: "IXONIA BANK",
    dba: "IXONIA BANK",
    nmls: "348970",
    lei: "",
    address: {
      street: "1945 N. Elston Ave.",
      city: "Chicago",
      state: "IL",
      zip: "60642",
    },
    isApproved: "Yes",
    isDualApproved: "No",
    delegatedStatus: "Active",
    nonDelegatedStatus: "InActive",
    delegatedApprovedDate: "10/11/2019",
    nonDelegatedApprovedDate: "",
    division: "NORTHEAST",
    delegatedAe: "Amy Collett",
    nonDelegatedAe: "",
    delegatedAr: "Nancy Considine",
    nonDelegatedAr: "",
    delegatedCrm: "Nathan Wehrheim",
    nonDelegatedCrm: "",
    contacts: [
      {
        id: 1,
        firstName: "Cathy",
        lastName: "Hernandez",
        jobTitle: "Closing Manager",
        email: "cathyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 2,
        firstName: "Cindy",
        lastName: "Hesslau",
        jobTitle: "Underwriting Manager",
        email: "cindyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 3,
        firstName: "Danielle",
        lastName: "Brosman",
        jobTitle: "-",
        email: "dveltri@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Other",
      },
    ],
    status: "Active",
  },
  {
    id: 3,
    name: "FIRST FEDERAL SAVINGS AND LOAN ASSOCIATION OF LAKEWOOD",
    dba: "FIRST FEDERAL SAVINGS AND LOAN ASSOCIATION OF LAKEWOOD",
    nmls: "698999",
    lei: "324762478sjdfgsfgshgsdfjh",
    address: {
      street: "1945 N. Elston Ave.",
      city: "Chicago",
      state: "IL",
      zip: "60642",
    },
    isApproved: "Yes",
    isDualApproved: "No",
    delegatedStatus: "Inactive",
    nonDelegatedStatus: "Active",
    delegatedApprovedDate: "",
    nonDelegatedApprovedDate: "12/31/2017",
    division: "MIDWEST",
    delegatedAe: "",
    nonDelegatedAe: "Amy Collett",
    delegatedAr: "",
    nonDelegatedAr: "Nancy Considine",
    delegatedCrm: "",
    nonDelegatedCrm: "Valerie Grace",
    contacts: [
      {
        id: 1,
        firstName: "Cathy",
        lastName: "Hernandez",
        jobTitle: "Closing Manager",
        email: "cathyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 2,
        firstName: "Cindy",
        lastName: "Hesslau",
        jobTitle: "Underwriting Manager",
        email: "cindyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 3,
        firstName: "Danielle",
        lastName: "Brosman",
        jobTitle: "-",
        email: "dveltri@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Other",
      },
    ],
    status: "Active",
  },
  {
    id: 4,
    name: "S&S FINANCIAL",
    dba: "S&S FINANCIAL",
    nmls: "7670900",
    lei: "324762478sjdfgsfgshgsdfjh",
    address: {
      street: "1945 N. Elston Ave.",
      city: "Chicago",
      state: "IL",
      zip: "60642",
    },
    isApproved: "Yes",
    isDualApproved: "Yes",
    delegatedStatus: "Active",
    nonDelegatedStatus: "Active",
    delegatedApprovedDate: "10/11/2019",
    nonDelegatedApprovedDate: "12/31/2017",
    division: "MIDWEST",
    delegatedAe: "Amy Collett",
    nonDelegatedAe: "Amy Collett",
    delegatedAr: "Nancy Considine",
    nonDelegatedAr: "Nancy Considine",
    delegatedCrm: "Nathan Wehrheim",
    nonDelegatedCrm: "Valerie Grace",
    contacts: [
      {
        id: 1,
        firstName: "Cathy",
        lastName: "Hernandez",
        jobTitle: "Closing Manager",
        email: "cathyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 2,
        firstName: "Cindy",
        lastName: "Hesslau",
        jobTitle: "Underwriting Manager",
        email: "cindyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 3,
        firstName: "Danielle",
        lastName: "Brosman",
        jobTitle: "-",
        email: "dveltri@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Other",
      },
    ],
    status: "Active",
  },
  {
    id: 5,
    name: "CONSUMER REAL ESTATE FINANCE CO.",
    dba: "CONSUMER REAL ESTATE FINANCE CO.",
    nmls: "3123123",
    lei: "324762478sjdfgsfgshgsdfjh",
    address: {
      street: "1945 N. Elston Ave.",
      city: "Chicago",
      state: "IL",
      zip: "60642",
    },
    isApproved: "Yes",
    isDualApproved: "Yes",
    delegatedStatus: "Active",
    nonDelegatedStatus: "Active",
    delegatedApprovedDate: "10/11/2019",
    nonDelegatedApprovedDate: "12/31/2017",
    division: "MIDWEST",
    delegatedAe: "Amy Collett",
    nonDelegatedAe: "Amy Collett",
    delegatedAr: "Nancy Considine",
    nonDelegatedAr: "Nancy Considine",
    delegatedCrm: "Nathan Wehrheim",
    nonDelegatedCrm: "Valerie Grace",
    contacts: [
      {
        id: 1,
        firstName: "Cathy",
        lastName: "Hernandez",
        jobTitle: "Closing Manager",
        email: "cathyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 2,
        firstName: "Cindy",
        lastName: "Hesslau",
        jobTitle: "Underwriting Manager",
        email: "cindyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 3,
        firstName: "Danielle",
        lastName: "Brosman",
        jobTitle: "-",
        email: "dveltri@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Other",
      },
    ],
    status: "Active",
  },
  {
    id: 6,
    name: "M SQUARED FINANCIAL LLC",
    dba: "M SQUARED FINANCIAL LLC",
    nmls: "767565",
    lei: "324762478sjdfgsfgshgsdfjh",
    address: {
      street: "1945 N. Elston Ave.",
      city: "Chicago",
      state: "IL",
      zip: "60642",
    },
    isApproved: "Yes",
    isDualApproved: "Yes",
    delegatedStatus: "Active",
    nonDelegatedStatus: "Active",
    delegatedApprovedDate: "10/11/2019",
    nonDelegatedApprovedDate: "12/31/2017",
    division: "MIDWEST",
    delegatedAe: "Amy Collett",
    nonDelegatedAe: "Amy Collett",
    delegatedAr: "Nancy Considine",
    nonDelegatedAr: "Nancy Considine",
    delegatedCrm: "Nathan Wehrheim",
    nonDelegatedCrm: "Valerie Grace",
    contacts: [
      {
        id: 1,
        firstName: "Cathy",
        lastName: "Hernandez",
        jobTitle: "Closing Manager",
        email: "cathyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 2,
        firstName: "Cindy",
        lastName: "Hesslau",
        jobTitle: "Underwriting Manager",
        email: "cindyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 3,
        firstName: "Danielle",
        lastName: "Brosman",
        jobTitle: "-",
        email: "dveltri@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Other",
      },
    ],
    status: "Active",
  },
  {
    id: 7,
    name: "ARCUS LENDING INC",
    dba: "ARCUS LENDING INC",
    nmls: "609899",
    lei: "324762478sjdfgsfgshgsdfjh",
    address: {
      street: "1945 N. Elston Ave.",
      city: "Chicago",
      state: "IL",
      zip: "60642",
    },
    isApproved: "Yes",
    isDualApproved: "Yes",
    delegatedStatus: "Active",
    nonDelegatedStatus: "Active",
    delegatedApprovedDate: "10/11/2019",
    nonDelegatedApprovedDate: "12/31/2017",
    division: "MIDWEST",
    delegatedAe: "Amy Collett",
    nonDelegatedAe: "Amy Collett",
    delegatedAr: "Nancy Considine",
    nonDelegatedAr: "Nancy Considine",
    delegatedCrm: "Nathan Wehrheim",
    nonDelegatedCrm: "Valerie Grace",
    contacts: [
      {
        id: 1,
        firstName: "Cathy",
        lastName: "Hernandez",
        jobTitle: "Closing Manager",
        email: "cathyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 2,
        firstName: "Cindy",
        lastName: "Hesslau",
        jobTitle: "Underwriting Manager",
        email: "cindyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 3,
        firstName: "Danielle",
        lastName: "Brosman",
        jobTitle: "-",
        email: "dveltri@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Other",
      },
    ],
    status: "Active",
  },
  {
    id: 8,
    name: "CAPITAL BANK, N.A.",
    dba: "CAPITAL BANK, N.A.",
    nmls: "348990",
    lei: "324762478sjdfgsfgshgsdfjh",
    address: {
      street: "1945 N. Elston Ave.",
      city: "Chicago",
      state: "IL",
      zip: "60642",
    },
    isApproved: "Yes",
    isDualApproved: "Yes",
    delegatedStatus: "Active",
    nonDelegatedStatus: "Active",
    delegatedApprovedDate: "10/11/2019",
    nonDelegatedApprovedDate: "12/31/2017",
    division: "MIDWEST",
    delegatedAe: "Amy Collett",
    nonDelegatedAe: "Amy Collett",
    delegatedAr: "Nancy Considine",
    nonDelegatedAr: "Nancy Considine",
    delegatedCrm: "Nathan Wehrheim",
    nonDelegatedCrm: "Valerie Grace",
    contacts: [
      {
        id: 1,
        firstName: "Cathy",
        lastName: "Hernandez",
        jobTitle: "Closing Manager",
        email: "cathyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 2,
        firstName: "Cindy",
        lastName: "Hesslau",
        jobTitle: "Underwriting Manager",
        email: "cindyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 3,
        firstName: "Danielle",
        lastName: "Brosman",
        jobTitle: "-",
        email: "dveltri@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Other",
      },
    ],
    status: "Active",
  },
  {
    id: 9,
    name: "O1NE MORTGAGE INC",
    dba: "O1NE MORTGAGE INC",
    nmls: "127516",
    lei: "324762478sjdfgsfgshgsdfjh",
    address: {
      street: "1945 N. Elston Ave.",
      city: "Chicago",
      state: "IL",
      zip: "60642",
    },
    isApproved: "Yes",
    isDualApproved: "Yes",
    delegatedStatus: "Active",
    nonDelegatedStatus: "Active",
    delegatedApprovedDate: "10/11/2019",
    nonDelegatedApprovedDate: "12/31/2017",
    division: "MIDWEST",
    delegatedAe: "Amy Collett",
    nonDelegatedAe: "Amy Collett",
    delegatedAr: "Nancy Considine",
    nonDelegatedAr: "Nancy Considine",
    delegatedCrm: "Nathan Wehrheim",
    nonDelegatedCrm: "Valerie Grace",
    contacts: [
      {
        id: 1,
        firstName: "Cathy",
        lastName: "Hernandez",
        jobTitle: "Closing Manager",
        email: "cathyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 2,
        firstName: "Cindy",
        lastName: "Hesslau",
        jobTitle: "Underwriting Manager",
        email: "cindyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 3,
        firstName: "Danielle",
        lastName: "Brosman",
        jobTitle: "-",
        email: "dveltri@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Other",
      },
    ],
    status: "Active",
  },
  {
    id: 10,
    name: "SUMMIT MORTGAGE CORPORATION-NMLS 1041",
    dba: "SUMMIT MORTGAGE CORPORATION-NMLS 1041",
    nmls: "456808",
    lei: "324762478sjdfgsfgshgsdfjh",
    address: {
      street: "1945 N. Elston Ave.",
      city: "Chicago",
      state: "IL",
      zip: "60642",
    },
    isApproved: "Yes",
    isDualApproved: "Yes",
    delegatedStatus: "Active",
    nonDelegatedStatus: "Active",
    delegatedApprovedDate: "10/11/2019",
    nonDelegatedApprovedDate: "12/31/2017",
    division: "MIDWEST",
    delegatedAe: "Amy Collett",
    nonDelegatedAe: "Amy Collett",
    delegatedAr: "Nancy Considine",
    nonDelegatedAr: "Nancy Considine",
    delegatedCrm: "Nathan Wehrheim",
    nonDelegatedCrm: "Valerie Grace",
    contacts: [
      {
        id: 1,
        firstName: "Cathy",
        lastName: "Hernandez",
        jobTitle: "Closing Manager",
        email: "cathyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 2,
        firstName: "Cindy",
        lastName: "Hesslau",
        jobTitle: "Underwriting Manager",
        email: "cindyh@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Cap Market Contact",
      },
      {
        id: 3,
        firstName: "Danielle",
        lastName: "Brosman",
        jobTitle: "-",
        email: "dveltri@anmtg.com",
        mobilePhone: "7733055626",
        contactType: "Other",
      },
    ],
    status: "Active",
  },
];

export default clientData;
