export default [
  {
    id: 1,
    Brand: "MRC",
    Channel: "Delegated",
    BillType: "EPO",
    TotalAmount: 500000,
    AmountPending: 201290,
    AmountBilled: 10500,
    AmountClosed: 30000,
    PaymentAdjustment: 5000,
  },
  {
    id: 2,
    Brand: "MRC",
    Channel: "Delegated",
    BillType: "EPD",
    TotalAmount: 601000,
    AmountPending: 0,
    AmountBilled: 0,
    AmountClosed: 601000,
    PaymentAdjustment: 601000,
  },
  {
    id: 3,
    Brand: "MRC",
    Channel: "Delegated",
    BillType: "Pairoff",
    TotalAmount: 800093,
    AmountPending: 0,
    AmountBilled: 0,
    AmountClosed: 0,
    PaymentAdjustment: 0,
  },
  {
    id: 4,
    Brand: "MRC",
    Channel: "Non-Delegated",
    BillType: "EPO",
    TotalAmount: 500000,
    AmountPending: 0,
    AmountBilled: 0,
    AmountClosed: 0,
    PaymentAdjustment: 0,
  },
  {
    id: 5,
    Brand: "MRC",
    Channel: "Non-Delegated",
    BillType: "EPD",
    TotalAmount: 8109093,
    AmountPending: 0,
    AmountBilled: 0,
    AmountClosed: 8109093,
    PaymentAdjustment: 8109093,
  },
  {
    id: 6,
    Brand: "MRC",
    Channel: "Non-Delegated",
    BillType: "Pairoff",
    TotalAmount: 800093,
    AmountPending: 0,
    AmountBilled: 0,
    AmountClosed: 800093,
    PaymentAdjustment: 800093,
  },
];
