const invoiceListData = [
  {
    invoiceId: 1201,
    batchId: 1001,
    branchId: 1,
    clientId: 1,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 1000,
    newAmount: 2000,
    status: "Pending",
    active: true,
  },
  {
    invoiceId: 1202,
    batchId: 1001,
    branchId: 2,
    clientId: 2,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 999,
    newAmount: 1999,
    status: "Pending",
    active: true,
  },
  {
    invoiceId: 1203,
    batchId: 1001,
    branchId: 1,
    clientId: 3,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 1430,
    newAmount: 560,
    status: "Pending",
    active: true,
  },
  {
    invoiceId: 1204,
    batchId: 1001,
    branchId: 3,
    clientId: 4,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 3487,
    newAmount: 2345,
    status: "Pending",
    active: true,
  },
  {
    invoiceId: 1205,
    batchId: 1001,
    branchId: 1,
    clientId: 5,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 32987,
    newAmount: 2437,
    status: "Pending",
    active: true,
  },
  {
    invoiceId: 1206,
    batchId: 1001,
    branchId: 1,
    clientId: 6,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 34567,
    newAmount: 12479,
    status: "Pending",
    active: true,
  },
  {
    invoiceId: 1207,
    batchId: 1001,
    branchId: 1,
    clientId: 7,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 74655,
    newAmount: 34767,
    status: "Pending",
    active: true,
  },
  {
    invoiceId: 1208,
    batchId: 1001,
    branchId: 1,
    clientId: 8,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 23424,
    newAmount: 96703,
    status: "Pending",
    active: true,
  },
  {
    invoiceId: 1209,
    batchId: 1001,
    branchId: 1,
    clientId: 9,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 12234,
    newAmount: 67867,
    status: "Pending",
    active: false,
  },
  {
    invoiceId: 1210,
    batchId: 1001,
    branchId: 1,
    clientId: 10,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 98599,
    newAmount: 32486,
    status: "Pending",
    active: false,
  },

  {
    invoiceId: 1301,
    batchId: 1002,
    branchId: 1,
    clientId: 1,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 1000,
    newAmount: 2000,
    status: "Billed",
    active: true,
  },
  {
    invoiceId: 1302,
    batchId: 1002,
    branchId: 2,
    clientId: 2,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 999,
    newAmount: 1999,
    status: "Billed",
    active: true,
  },
  {
    invoiceId: 1303,
    batchId: 1002,
    branchId: 1,
    clientId: 3,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 1430,
    newAmount: 560,
    status: "Billed",
    active: true,
  },
  {
    invoiceId: 1304,
    batchId: 1002,
    branchId: 3,
    clientId: 4,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 3487,
    newAmount: 2345,
    status: "Billed",
    active: true,
  },
  {
    invoiceId: 1305,
    batchId: 1002,
    branchId: 1,
    clientId: 5,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 32987,
    newAmount: 2437,
    status: "Billed",
    active: true,
  },
  {
    invoiceId: 1306,
    batchId: 1002,
    branchId: 1,
    clientId: 6,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 34567,
    newAmount: 12479,
    status: "Billed",
    active: true,
  },
  {
    invoiceId: 1307,
    batchId: 1002,
    branchId: 1,
    clientId: 7,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 74655,
    newAmount: 34767,
    status: "Billed",
    active: true,
  },
  {
    invoiceId: 1308,
    batchId: 1002,
    branchId: 1,
    clientId: 8,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 23424,
    newAmount: 96703,
    status: "Billed",
    active: true,
  },
  {
    invoiceId: 1309,
    batchId: 1002,
    branchId: 1,
    clientId: 9,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 12234,
    newAmount: 67867,
    status: "Billed",
    active: false,
  },
  {
    invoiceId: 1310,
    batchId: 1002,
    branchId: 1,
    clientId: 10,
    contacts: "dummy@mrcooper.com",
    outstandingAmount: 98599,
    newAmount: 32486,
    status: "Billed",
    active: false,
  },
];

export default invoiceListData;
