const adjustmentData = [
  {
    id: 1,
    billTypeId: 1,
    sourceBillTypeId: 1,
    adjustmentTypeId: 1,
    adjustmentSubTypeId: 1,
    status: "Pending",
    amountDue: 709.1,
    comments: "",
    createdBy: "Connie Husdon",
    createdDatetime: "09/10/2021 11:33 AM",
    modifiedBy: "Connie Hudson",
    modifiedDatetime: "09/10/2021 11:33 AM",
  },
  {
    id: 2,
    billTypeId: 1,
    sourceBillTypeId: 1,
    adjustmentTypeId: 1,
    adjustmentSubTypeId: 1,
    status: "Pending",
    amountDue: 251.5,
    comments: "",
    createdBy: "Connie Husdon",
    createdDatetime: "09/10/2021 11:33 AM",
    modifiedBy: "Connie Hudson",
    modifiedDatetime: "09/10/2021 11:33 AM",
  },
  {
    id: 3,
    billTypeId: 1,
    sourceBillTypeId: 2,
    adjustmentTypeId: 1,
    adjustmentSubTypeId: 1,
    status: "Pending",
    amountDue: 3043.2,
    comments: "",
    createdBy: "Connie Husdon",
    createdDatetime: "09/10/2021 11:33 AM",
    modifiedBy: "Connie Hudson",
    modifiedDatetime: "09/10/2021 11:33 AM",
  },
  {
    id: 4,
    billTypeId: 1,
    sourceBillTypeId: 3,
    adjustmentTypeId: 1,
    adjustmentSubTypeId: 1,
    status: "Pending",
    amountDue: 550.12,
    comments: "",
    createdBy: "Connie Husdon",
    createdDatetime: "09/10/2021 11:33 AM",
    modifiedBy: "Connie Hudson",
    modifiedDatetime: "09/10/2021 11:33 AM",
  },
];

export default adjustmentData;
